# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1455906289);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1455906409);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1455906649);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1455906169);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1455906049);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1455906529);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 2);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 34);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.safebrowsing.provider.google.lastupdatetime", "1455913719607");
user_pref("browser.safebrowsing.provider.google.nextupdatetime", "1455915633607");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1455913720496");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1455917320496");
user_pref("browser.search.countryCode", "NL");
user_pref("browser.search.region", "NL");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20160211213400");
user_pref("browser.slowStartup.averageTime", 1137);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20160211213400");
user_pref("browser.startup.homepage_override.mstone", "44.0.2");
user_pref("browser.toolbarbuttons.introduced.pocket-button", true);
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1455973487168");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1455887101629");
user_pref("datareporting.policy.firstRunTime", "1455887087168");
user_pref("datareporting.sessions.current.activeTicks", 4);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 1272);
user_pref("datareporting.sessions.current.main", 14);
user_pref("datareporting.sessions.current.sessionRestored", 1152);
user_pref("datareporting.sessions.current.startTime", "1455913714609");
user_pref("datareporting.sessions.current.totalTime", 27);
user_pref("datareporting.sessions.currentIndex", 5);
user_pref("datareporting.sessions.previous.0", "{\"s\":1455887085519,\"a\":0,\"t\":1,\"c\":false,\"m\":14,\"fp\":314,\"sr\":-1}");
user_pref("datareporting.sessions.previous.1", "{\"s\":1455887090586,\"a\":2,\"t\":11,\"c\":false,\"m\":31,\"fp\":1116,\"sr\":1044}");
user_pref("datareporting.sessions.previous.2", "{\"s\":1455899672628,\"a\":1,\"t\":27,\"c\":false,\"m\":54,\"fp\":14348,\"sr\":1471}");
user_pref("datareporting.sessions.previous.3", "{\"s\":1455899788095,\"a\":1,\"t\":21,\"c\":false,\"m\":42,\"fp\":3045,\"sr\":1595}");
user_pref("datareporting.sessions.previous.4", "{\"s\":1455905928705,\"a\":1,\"t\":7692,\"c\":true,\"m\":30,\"fp\":211829,\"sr\":1501}");
user_pref("dom.apps.reset-permissions", true);
user_pref("dom.mozApps.used", true);
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 17);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:44.0.2");
user_pref("extensions.getAddons.cache.lastUpdate", 1455906290);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.hotfix.lastVersion", "20160106.01");
user_pref("extensions.lastAppVersion", "44.0.2");
user_pref("extensions.lastPlatformVersion", "44.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.xpiState", "{\"app-global\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"e\":true,\"v\":\"44.0.2\",\"st\":1455228322000,\"mt\":1455228322000}}}");
user_pref("gecko.buildID", "20160211213400");
user_pref("gecko.mstone", "44.0.2");
user_pref("idle.lastDailyNotification", 1455887305);
user_pref("layout.css.devPixelsPerPx", "-1.0");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1455887152);
user_pref("media.gmp-gmpopenh264.version", "1.5.3");
user_pref("media.gmp-manager.buildID", "20160211213400");
user_pref("media.gmp-manager.lastCheck", 1455887152);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateClearSavedPwdsOnExit", true);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("toolkit.startup.last_success", 1455913714);
user_pref("toolkit.telemetry.cachedClientID", "d766d684-7479-4c88-88a0-92393bab2ff3");
user_pref("toolkit.telemetry.previousBuildID", "20160211213400");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
